import { Building2, Save, ShieldCheck } from "lucide-react";
import { saveSettings } from "@/app/actions";
import { SignOutButton } from "@/components/sign-out-button";
import { getBusinessSettings } from "@/lib/data";
import { isSupabaseConfigured } from "@/lib/supabase/server";

export const metadata = { title: "Settings" };

export default async function SettingsPage() {
  const settings = await getBusinessSettings();
  const configured = isSupabaseConfigured();
  return <><div className="page-heading"><div><p className="eyebrow">Your business</p><h1>Settings</h1><p className="subtle">These details are snapshotted onto finalized invoices.</p></div></div><form action={saveSettings} className="settings-grid"><section className="section-card"><div className="section-heading"><div><h2><Building2 /> Tutor details</h2><p>Your identity on invoices.</p></div></div><div className="stack-form"><label>Name<input name="tutorName" defaultValue={settings.tutorName} required /></label><div className="form-split"><label>Email<input name="tutorEmail" type="email" defaultValue={settings.tutorEmail} /></label><label>Phone<input name="tutorPhone" defaultValue={settings.tutorPhone} /></label></div><label>Address<textarea name="tutorAddress" rows={3} defaultValue={settings.tutorAddress} /></label><label>Payment details<textarea name="bankDetails" rows={4} defaultValue={settings.bankDetails} /></label></div></section><section className="section-card"><div className="section-heading"><div><h2>Default payer</h2><p>Used for all-students invoices.</p></div></div><div className="stack-form"><label>Business or payer name<input name="defaultPayerName" defaultValue={settings.defaultPayerName} /></label><label>Email<input name="defaultPayerEmail" type="email" defaultValue={settings.defaultPayerEmail} /></label><label>Address<textarea name="defaultPayerAddress" rows={3} defaultValue={settings.defaultPayerAddress} /></label><div className="form-split"><label>Payment terms (days)<input name="paymentTermsDays" type="number" min="0" defaultValue={settings.paymentTermsDays} /></label><label>Invoice prefix<input name="invoicePrefix" pattern="[A-Za-z0-9-]+" defaultValue={settings.invoicePrefix} /></label></div><label>Timezone<select name="timezone" defaultValue={settings.timezone}><option value="Africa/Johannesburg">Africa/Johannesburg</option><option value="Africa/Harare">Africa/Harare</option><option value="UTC">UTC</option></select></label></div></section><div className="settings-actions"><span><ShieldCheck /> Currency is fixed to ZAR. No tax is applied.</span><button className="button-primary" type="submit"><Save size={17} /> Save settings</button></div></form>{configured && <div className="signout-row"><SignOutButton /></div>}</>;
}
